### ISSUE TITLE
Add additional TFM so STJ can be provided by the framework

### ISSUE THREAD

**Issue by thompson-tomo** [IvanJosipovic/YamlDotNet.System.Text.Json#93]
**Is your feature request related to a problem? Please describe.**
I want to minimise dependencies in my project by utilising framework dependencies wherever possible

**Describe the solution you'd like**
I want the package to not have an explicit dependency on System.Text.Json as it can be provided by the framework when targeting net 6. 

**Describe alternatives you've considered**
Accept the additional dependency

**Additional context**
n/a

**Comment by IvanJosipovic** [comment]
Hey, please try version 1.4.0.

**Comment by thompson-tomo** [comment]
Implemented with https://github.com/IvanJosipovic/YamlDotNet.System.Text.Json/commit/071b087355937c320981cc1fc95a4099f7e4abfa
